/**  HomeMade by shoe[box]   Redistribution and use in source and binary forms, with or without   modification, are permitted provided that the following conditions are  met:  * Redistributions of source code must retain the above copyright notice,     this list of conditions and the following disclaimer.    * Redistributions in binary form must reproduce the above copyright    notice, this list of conditions and the following disclaimer in the     documentation and/or other materials provided with the distribution.    * Neither the name of shoe[box] nor the names of its     contributors may be used to endorse or promote products derived from     this software without specific prior written permission.  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS  IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,  THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR  PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR   CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,  EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR  PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF  LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING  NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.*/package org.shoebox.collections {	import org.shoebox.utils.system.Signal;	import org.shoebox.utils.logger.Logger;			/**	* org.shoebox.collections.GlobalVars	* @author shoebox	*/	public class GlobalVars extends Signal {				public var hCONTENT			: HashMap;				// -------o constructor					/**			* Constructor of the GlobalVars class			*			* @public			* @return	void			*/			public function GlobalVars( e : SingletonEnforcer ) : void {				hCONTENT = new HashMap( false );			}		// -------o public						/**
			* hasValue function
			* @public
			* @param 
			* @return
			*/
			static public function hasValue( key : * ) : Boolean {
				return getInstance( ).hCONTENT.containsKey( key );
			}						/**			* addItem function			* @public			* @param 			* @return			*/			static public function setValue( key : * , value : * ) : Boolean {								var 	oGV : GlobalVars = getInstance( );														var oldValue : * = oGV.hCONTENT.getValue( key );								if( oldValue == undefined || oldValue !== value ){					oGV.hCONTENT.addItem( key , value );					oGV.emit( key , key , oldValue , value );					return true;					}								return false;			}						/**			* getVar function			* @public			* @param 			* @return			*/			static public function getValue( key : * ) : * {				return getInstance().hCONTENT.getValue(key);			}						/**			* toString function			* @public			* @param 			* @return			*/			static public function toString() : String {								var sRES : String = 'Global variables \n';				var k : String;				var a : Array = getInstance().hCONTENT.getKeys();				for each( k in a )					sRES += k + ' \t = ' + getInstance().hCONTENT.getValue( k );									return sRES;			}						/**
			* register function
			* @public
			* @param 
			* @return
			*/
			static public function register( f : Function , s : String = null , prio : uint = 0 , bOS : Boolean = false ) : Boolean {
				return getInstance( ).connect( f , s , prio , bOS );
			}					// -------o protected					// -------o misc			public static function trc(...args : *) : void {				Logger.log(GlobalVars, args);			}						/**			* Return the singleton instance of the class			* @public			* @return instance of the class (Vars)			*/			static public function getInstance() : GlobalVars {								if( !__instance )					__instance = new GlobalVars( new SingletonEnforcer() );												return __instance;			}			protected static var __instance			: GlobalVars = null;	}}internal class SingletonEnforcer{}